FROM public.ecr.aws/d3j8x8q7/olympus-base:latest

RUN pip3 install --no-cache-dir uv==0.1.45 --break-system-packages || pip3 install --no-cache-dir uv==0.1.45

WORKDIR /app
COPY . .

RUN uv pip install --system --frozen -e ".[dev]" || uv pip install --break-system-packages --frozen -e ".[dev]"
RUN npm ci --include=dev

ENV PATH="/app/node_modules/.bin:${PATH}"

CMD ["/bin/bash"]
